### ISSUE TITLE
Support Photo Titles

### ISSUE THREAD

**Issue by markwk** [rprieto/thumbsup#14]
I really like what you are doing here. Simple and understandable approach to static photo gallery generation and using nodejs to boot! Bravo! 

I'd like to add Title support so that title gets shown for images. I guess the step would be generate some of that info into metadata.json as a new line so we'd end up with something like

  "filename.jpg": {
    "fileDate": 1412499522000,
    "mediaDate": 1408641125000,
    "mediaType": "photo",
   "title":"title-here-using-filename"
  },

**Comment by rprieto** [comment]
Hi @markwk, closing in favour of #24 to have all conversations in one place. We now support `EXIF` captions, and we can add an option to default to the file name. Thanks for the suggestions!
