### ISSUE TITLE
Minor Directory and Path Issues

### ISSUE THREAD

**Issue by dravenst** [rprieto/thumbsup#23]
Great project!  I've been looking for something like this for quite awhile.  

A few fix ideas.

1) I was seeing an error when I had additional levels in them with sub-directories with photos in them.  I think the fix is to change this line in metadata.js from this:

glob('**/*.{jpg,jpeg,png,mp4,mov,mts,m2ts}', globOptions, callback);

to this:

glob('{,*/}*.{jpg,jpeg,png,mp4,mov,mts,m2ts}', globOptions, callback);

2) I was running into issues on Windows with the output web files having the slashes in the wrong direction.  A simple change to the model.js file to find/replace slashes after the join function was helpful.  I found a replaceAll function to do this:

String.prototype.replaceAll = function(str1, str2, ignore) 
  {
    return this.replace(new RegExp(str1.replace(/([\/\,\!\\\^\$\{\}\[\]\(\)\.\*\+\?\|\<\>\-\&])/g,"\\$&"),(ignore?"gi":"g")),(typeof(str2)=="string")?str2.replace(/\$/g,"$$$$"):str2);
  } 

then update each of the join statements to something like this:
 thumb:     path.join('media', 'thumbs', file).replaceAll('\\','/'),

3) I was getting an uncaught exception in exif.js when it was processing a bad file.  I added a try/catch block around the exif.create() statement to fix it.

**Comment by rprieto** [comment]
Thanks @dravenst, I pushed the fix for (2) and (3).

If you're still interested in (1), do you mind raising a separate issue / feature request? It probably requires a different conversation: for new `thumbsup` only officially supports 1 level of subfolders (galleries), so we could discuss what should happen for several levels.
