### ISSUE TITLE
 Please help! ! !

### ISSUE THREAD

**Issue by mba811** [rprieto/thumbsup#26]
Romain Prieto Hello!

Great works, what specific installation in a Mac-specific methods deployed to Dropbox shared galleries! Thank you.

In the End Operation:

brew install Node
brew install graphicsmagick
brew install ffmpeg

npm install -g thumbsup

How then should continue?

Thank you very much for your help!

**Comment by rprieto** [comment]
Hi,

If you installed all the dependencies, you should just be able to run:

```bash
thumbsup --input "/media/photos" --output "./website" --title "My holidays" --thumb-size 200 --large-size 1500 --full-size-photos true --sort-folders date --css "./custom.css" --google-analytics "UA-999999-9"
```

You can also put all the arguments in a config file, as shown in the README.

Just to clarify though, `thumbsup` create a gallery *similar* to Dropbox shared galleries.
It's up to you to host it anywhere, for example on AWS S3.

**Comment by rprieto** [comment]
Hi, assuming this is solved. Please let me know if you still need help and we can update the `README` to be clearer.
