### ISSUE TITLE
Issues with sorting and timestamps

### ISSUE THREAD

**Issue by kremlinkev** [rprieto/thumbsup#30]
I found a few issues with the app:

1) When adding albums and sorting by date, I found I wanted the newest first however there was no way to change sort order
2) When sorting by date, and lack of exif data, it would use ctime instead of mtime for timestamp entries. This caused issues when touching up photos as this would change the ctime which cannot be changed without unmounting the filesystem and modifying the inode vs being able to arbitrarily set the mtime (eg via touch)

I know very little about javascript, and even less about node, so I humbly present my naive approach on how I solved the issues with config toggles.

**Comment by rprieto** [comment]
Thanks for the comments - all very valid!
About 1:
- an option sounds great, maybe `--sort-order` to make it more obvious than `--order`?
- should it also apply to how photos are sorted, or just the albums?
About 2:
- very good pickup, which makes me wonder if there's ever really a reason to sort by `ctime`. Also, the current logic had `max(ctime,mtime)` which in hindsight is actually the same as `ctime`, right?

**Comment by kremlinkev** [comment]
Re 1:
I agree `--sort-order` makes more sense. I'll change it up.
I only really cared about albums :} If I am reading the code right, what I changed only changes albums? So maybe `--album-sort-order`` ?

Re 2:
I was wondering about your decision to do that, functionally I would assume it would be the same, but there's technically nothing preventing you from setting mtime in the future:

```
$ touch -d20200220 test ; stat test
  File: `test'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d	Inode: 742311753   Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   kevin)   Gid: ( 1000/   kevin)
Access: 2020-02-20 00:00:00.000000000 -0600
Modify: 2020-02-20 00:00:00.000000000 -0600
Change: 2015-10-16 15:52:04.000000000 -0500
 Birth: -
```

I guess the tradeoff of leaving it in there vs just always going off of mtime would be overload of config options vs crazy graybeard who wants to do something insane. I defer to how you want to handle it :}

Additionally, I have no experience with javascript so I don't even know if my code is "best practice" let alone correct. But I can at least vouch for its functionality (it ran and did what it was supposed to do).

**Comment by rprieto** [comment]
Right now, photos are always sorted by date (ascending) and the only album sorting option is `--sort-folders [name|date]`.

I like your idea, seems more future proof. What about:

```bash
--sort-albums-by [name|date]
--sort-albums-order [asc|desc]
--sort-photos-by [name|date]
--sort-photos-order [asc|desc]
```

We don't have to implement it all now, but that could be a nice goal.

Regarding `ctime`/`mtime`, I'm tempted to go simple and avoid option overload :smile: Let me just run a check - there's a several-thousand-photos folder on which I run `thumbsup`, I'll check if `ctime` is always greater than `mtime` or if I can find edge cases.

**Comment by kremlinkev** [comment]
Amended original PR, the changes to trunk are as follows:
CHANGE: Config opt `--sort-folders` is now `--sort-albums-by`
CHANGE: Drop ctime in favor of ctime for timestamp
ENHANCEMENT: Added `--sort-albums-order` to change between ascending and descending orders

I think ditching ctime is best, since most changes to mtime will update ctime, but for the purpose of curating a gallery mtime is superior due to the ability to arbitrarily set it.

It might be worth noting that the config nob has changed, so previous users might still be expecting `--sort-folders`.

On the subject of being pedantic, consider `--sort-photos` to `--sort-media` since you also accept video as an acceptable format.

**Comment by rprieto** [comment]
Sounds great, and good idea about `--sort-media-by/order` :+1:
Let's take this to the PR! Mind if I close the issue?
