### ISSUE TITLE
On Mac OS X 10.11.3 100% CPU hang

### ISSUE THREAD

**Issue by crookedstorm** [rprieto/thumbsup#36]
I can't seem to glean much debugging info, but I can very consistently reproduce a 100% CPU (node process) hang on this step every time I have tried running this with a single photo and one subdir.  
thumbsup --input ./inputdir --output ./outputdir
List all files      [====================] 1/1 files
Update metadata     [====================] 1/1 files
Photos (large)      [====================] 1/1 files
Photos (thumbs)     [====================] 1/1 files
Videos (resized)    [====================] up to date
Videos (poster)     [====================] up to date
Videos (thumbs)     [====================] up to date
Static website  <---- here's the hang

**Comment by rprieto** [comment]
Hi, thanks for raising that! This was a problem with Node 5 compatibility (and maybe Node 4 too, I haven't tried). Just published version `1.1.2`  that should fix it, let me know how it goes!

**Comment by crookedstorm** [comment]
Runs perfect!  Thanks.
